### ISSUE TITLE
How to create file "warmup_k_path"?

### ISSUE THREAD

**Issue by viet24dung** [VinAIResearch/blur-kernel-space-exploring#3]
Thank you for this repo is really awesome. But I have a small question:
how is the "warmup_k_path" file created, what is it used for in the deblur process.

**Comment by P0lyFish** [comment]
Hi, thanks for your interest.
If you mean the "warmup_k.pth", it is a random kernel extracted by the kernel extractor. Before doing image deblurring, we initialize the blur kernel with a random kernel to stabilize the optimization process.
To generate a warmup_k.pth, you can modify the "data_augmentation.py"., for example, add `torch.save("kernel.pth", kernel) before  L119.
