### ISSUE TITLE
Output of the PostProcessBlock added to the input sharp image.

### ISSUE THREAD

**Issue by pvitoria** [VinAIResearch/blur-kernel-space-exploring#5]
Hi! 
First of all congratulations for the work.

In the code, the output of the postprocessblock is added to the input  sharp image in order to generate the blur image.
In the paper i do not find any place that says explicitly that the output is a residual to be added to the residual in order to create the blur image. is it a bug? should be added? Or F computes directly the blur image?

Thanks!

**Comment by P0lyFish** [comment]
Thank you for your interest!

It's not a bug, the output of the PostprocessBlock is added to the sharp image to generate the corresponding blurry image. We did not include this in the paper, sorry for making you confused.
