### ISSUE TITLE
Generic_deblur.py result image using pretrained weights is different from the paper.

### ISSUE THREAD

**Issue by sjmin9868** [VinAIResearch/blur-kernel-space-exploring#7]
Hi. I'm trying to deblur face01.png image of blur_faces. While I was running generic_deblur.py with default settings with pretrained weights of GOPRO_woVAE.pth and the results were unsatisfactory. I checked that the generate_blur.py made satisfactory results of blur generating process. For prerequisites, I'm using the versons below.

- Python = 3.9.5
- Pytorch = 1.9.0
- CUDA = 10.1

I tried to use Pytorch version of 1.4.0 but version error occured, so I used 1.9.0.
I want to get results in the paper for face01.png image, and if there is anything I should tune or change, please let me know.
Thank you for your help.

**Comment by P0lyFish** [comment]
Thank you for your interest!
`face01.png` is generated by `domain_specific_deblur.py`, not `generic_deblur.py`. Please refer to [this section](https://github.com/VinAIResearch/blur-kernel-space-exploring#deblurring-using-sharp-image-prior) for more information.
