### ISSUE TITLE
Missing pretained models pth files

### ISSUE THREAD

**Issue by ckinsung85** [VinAIResearch/blur-kernel-space-exploring#8]
Missing pth pretrained models

http://public.vinai.io/models/blur-kernel-space-exploring/REDS_woVAE.pth
http://public.vinai.io/models/blur-kernel-space-exploring/GOPRO_woVAE.pth
http://public.vinai.io/models/blur-kernel-space-exploring/GOPRO_wVAE.pth
http://public.vinai.io/models/blur-kernel-space-exploring/mix_woVAE.pth

All the above links do not work. 

Any other alternative sources for downloading?

**Comment by P0lyFish** [comment]
I have updated the download links of the pretrained models. Please check again.
Sorry for the inconvenience.
